import type { Metadata } from 'next'
import { Martian_Mono } from 'next/font/google'
import './globals.scss'

const martianMono = Martian_Mono({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={martianMono.className}>{children}</body>
    </html>
  )
}
